'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class _default1

    '''<summary>
    '''pageHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pageHeader As Global.System.Web.UI.UserControl

    '''<summary>
    '''theForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents theForm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''errorMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errorMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''surveyQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents surveyQuestions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''surveyButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents surveyButton As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''genderDisclaimer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents genderDisclaimer As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pageFooter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pageFooter As Global.System.Web.UI.UserControl
End Class
