'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Feedback

    '''<summary>
    '''surveyImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents surveyImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''printThisBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents printThisBtn As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''consultBtn1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents consultBtn1 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''readMoreBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents readMoreBtn As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''forwardLnk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents forwardLnk As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''forwardBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents forwardBtn As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''feedbackLnk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents feedbackLnk As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''feedbackBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents feedbackBtn As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ProgramScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProgramScore As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LetterGrade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LetterGrade As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowA2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowA2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PA2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PA2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowA As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowA1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowA1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PA1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PA1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowB2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowB2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PB2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PB2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowB As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowB1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowB1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PB1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PB1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowC2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PC2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowC As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowC1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PC1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowD2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowD2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PD2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PD2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowD As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowD1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowD1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PD1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PD1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowF As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''PF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PF As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''noteHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noteHead As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''notes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''warnings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents warnings As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''InstScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InstScore As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''theScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents theScore As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''budget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents budget As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''instDebug control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents instDebug As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''notes2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notes2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''warnings2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents warnings2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowInstA2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowInstA2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''IA2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IA2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowInstA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowInstA As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''IA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowInstA1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowInstA1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''IA1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IA1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowInstB2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowInstB2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''IB2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IB2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowInstB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowInstB As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''IB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowInstB1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowInstB1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''IB1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IB1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowInstC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowInstC2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''IC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IC2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowInstC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowInstC As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''IC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowInstC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowInstC1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''IC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IC1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowInstD2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowInstD2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ID2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ID2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowInstD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowInstD As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ID0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ID0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowInstD1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowInstD1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ID1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowInstF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowInstF As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''IF0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IF0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''otherSurvey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents otherSurvey As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''research1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents research1 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''research2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents research2 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''openPrinterPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents openPrinterPage As Global.System.Web.UI.WebControls.Literal
End Class
